version: "3.9"
services:
  # Database mongodb
  trn_mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./trn_data:/data/db
    ports:
      - 27017:27017
    restart: always
    networks:
      - default

  # Frontend
  frontend:
    build:
      context: ./www
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/usr/share/nginx/html
    ports:
      - 80:80
    networks:
      - default
    links:
      - trn_auth

  # API Auth
  trn_auth:
    build:
      context: ./api
      dockerfile: Dockerfile.auth
    working_dir: /app
    environment:
      NODE_ENV: production
      DB_HOST: trn_mongodb
      DB_PORT: 27017
      DB_USERNAME: admin
      DB_PASSWORD: 1234
      DB_DATABASE: trn
    ports:
      - 30000:30000
    command: node server/server.js
    networks:
      - default
    links:
      - trn_mongodb
    depends_on:
      - trn_mongodb
      # API staff
  trn_staff:
    build:
      context: ./api
      dockerfile: Dockerfile.staff
    working_dir: /app
    environment:
      NODE_ENV: production
      DB_HOST: trn_mongodb
      DB_PORT: 27017
      DB_USERNAME: admin
      DB_PASSWORD: 1234
      DB_DATABASE: trn
    ports:
      - 31000:31000
    command: node server/server.js
    networks:
      - default
    links:
      - trn_mongodb
    depends_on:
      - trn_mongodb
      # API member
  trn_member:
    build:
      context: ./api
      dockerfile: Dockerfile.member
    working_dir: /app
    environment:
      NODE_ENV: production
      DB_HOST: trn_mongodb
      DB_PORT: 27017
      DB_USERNAME: admin
      DB_PASSWORD: 1234
      DB_DATABASE: trn
    ports:
      - 32000:32000
    command: node server/server.js
    networks:
      - default
    links:
      - trn_mongodb
    depends_on:
      - trn_mongodb
      # API master data
  trn_master_data:
    build:
      context: ./api
      dockerfile: Dockerfile.masterData
    working_dir: /app
    environment:
      NODE_ENV: production
      DB_HOST: trn_mongodb
      DB_PORT: 27017
      DB_USERNAME: admin
      DB_PASSWORD: 1234
      DB_DATABASE: trn
    ports:
      - 35000:35000
    command: node server/server.js
    networks:
      - default
    links:
      - trn_mongodb
    depends_on:
      - trn_mongodb

  trn_deposit:
    build:
      context: ./api
      dockerfile: Dockerfile.deposit
    working_dir: /app
    environment:
      NODE_ENV: production
      DB_HOST: trn_mongodb
      DB_PORT: 27017
      DB_USERNAME: admin
      DB_PASSWORD: 1234
      DB_DATABASE: trn
    ports:
      - 33000:33000
    command: node server/server.js
    networks:
      - default
    links:
      - trn_mongodb
    depends_on:
      - trn_mongodb
  trn_withdraw:
    build:
      context: ./api
      dockerfile: Dockerfile.withdraw
    working_dir: /app
    environment:
      NODE_ENV: production
      DB_HOST: trn_mongodb
      DB_PORT: 27017
      DB_USERNAME: admin
      DB_PASSWORD: 1234
      DB_DATABASE: trn
    ports:
      - 34000:34000
    command: node server/server.js
    networks:
      - default
    links:
      - trn_mongodb
    depends_on:
      - trn_mongodb
networks:
  default:
    external:
      name: local_network
